name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          # This command finds the specified JavaScript files and runs JSHint on them
          # The --esversion 8 flag tells JSHint to use modern JavaScript standards
          find ./giftlink-backend -name app.js -exec jshint --esversion 8 {} +
          find ./giftlink-backend/routes -name authRoutes.js -exec jshint --esversion 8 {} +
          find ./giftlink-backend/routes -name giftRoutes.js -exec jshint --esversion 8 {} +
          find ./giftlink-backend/routes -name searchRoutes.js -exec jshint --esversion 8 {} +
          echo "Linted all the specified js files successfully"

  client_build:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run Build
        run: |
          cd giftlink-frontend
          npm install
          npm run build
          echo "Client-side build successfully"
